### ISSUE TITLE
requirements for your system 'windows_amd64'

### ISSUE THREAD

**Issue by Linjieqiang** [pioarduino/platform-espressif32#66]
![image](https://github.com/user-attachments/assets/ebef3623-4174-4418-a72f-b42dfb6b8e33)

> Tool Manager: Installing espressif/framework-arduinoespressif32-libs
> UnknownPackageError: Could not find the package with 'espressif/framework-arduinoespressif32-libs' requirements for your system 'windows_amd64'

**Comment by Fakepng** [comment]
I ran into the same problem. I switch to the development version
```
[env:development]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = ...
...
```

I hope it works for you too.

**Comment by Jason2866** [comment]
Without posting the setup, can't help.

**Comment by OrhanYigitDurmaz** [comment]
For some reason Fakepng's solution work, but whenever i add the tinyusb library i get this: 
```python
Removing unused dependencies...
Library Manager: Installing adafruit/Adafruit TinyUSB Library @ ^3.4.1
Unpacking  [####################################]  100%
Library Manager: Adafruit TinyUSB Library@3.4.1 has been installed!
Library Manager: Resolving dependencies...
AttributeError: Traceback (most recent call last):
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\click\core.py", line 1157, in __call__    
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\click\core.py", line 1078, in main        
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\run\cli.py", line 145, in cli
    process_env(
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\run\cli.py", line 208, in process_env
    ).process()
      ^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\run\processor.py", line 81, in process
    install_project_env_dependencies(
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\package\commands\install.py", line 133, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\package\commands\install.py", line 252, in _install_project_env_libraries    env_lm.install(
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\package\manager\_install.py", line 47, in install
    pkg = self._install(spec, skip_dependencies=skip_dependencies, force=force)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\package\manager\_install.py", line 130, in _install
    self.install_dependencies(pkg)
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\package\manager\_install.py", line 143, in install_dependencies
    self.install_dependency(dependency)
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\package\manager\library.py", line 89, in install_dependency
    not_builtin_conds.append(not self.is_builtin_lib(spec.name))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\package\manager\library.py", line 120, in is_builtin_lib
    for storage in cls.get_builtin_libs():
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\util.py", line 57, in wrapper
    self.cache[key] = (time.time(), func(*args, **kwargs))
                                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\package\manager\library.py", line 104, in get_builtin_libs
    p = PlatformFactory.new(pkg)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan\.platformio\penv\Lib\site-packages\platformio\platform\factory.py", line 79, in new
    platform_cls = getattr(
                   ^^^^^^^^
AttributeError: module 'platformio.platform.platform' has no attribute 'PlatformPlatform'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================
```

Is this a problem with the tinyusb library?

**Comment by OrhanYigitDurmaz** [comment]
yes it was a library issue. the library.json on tinyusb library is very outdated and doesnt have the fields that platformio depends.

Tried it with: 
```ini
lib_deps = 
	https://github.com/OrhanYigitDurmaz/Adafruit_TinyUSB_Arduino.git#master
```
and it works. No problems.

**Comment by Zeron** [comment]
I get the same error: 
`Tool Manager: Installing espressif/framework-arduinoespressif32-libs
UnknownPackageError: Could not find the package with 'espressif/framework-arduinoespressif32-libs' requirements for your system 'windows_amd64'`

when using platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
but it works with platform = https://github.com/pioarduino/platform-espressif32.git#develop

No third party libraries.

**Comment by OrhanYigitDurmaz** [comment]
> I get the same error: `Tool Manager: Installing espressif/framework-arduinoespressif32-libs UnknownPackageError: Could not find the package with 'espressif/framework-arduinoespressif32-libs' requirements for your system 'windows_amd64'`
> 
> when using platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip but it works with platform = https://github.com/pioarduino/platform-espressif32.git#develop
> 
> No third party libraries.

thats because fix was made, but not yet made into a full release. You can keep using the develop branch or you're worried about instability issues, you can fork the repo itslef and make it point to your repo.
